### ISSUE TITLE
Error if MSI is not installed

### ISSUE THREAD

**Issue by gene-roussetos** [dotmailer/dotdigital-magento2-extension-inventory#1]
Hi,

When `ddg_automation_catalog_sync` cron is executed, the following error is triggered
```
Cannot instantiate interface Magento\InventorySalesApi\Api\GetProductSalableQtyInterface
```

Our application does not use MSI (it's removed with composer `replace`) so the interface does not exist.

- Adobe Commerce Version -> `2.4.5-p2`
- DotDigital module versions:
  - `dotdigital/dotdigital-magento2-os-package` ->  `1.5.5`
  - `dotdigital/dotdigital-magento2-extension-enterprise` -> `1.10.3`

We have disabled the module with `bin/magento module:disable Dotdigitalgroup_Inventory`. It feels that this should be sufficient.
Is there a better approach you would propose or any more checking you would need to add your end?

Thanks in advance

**Comment by sta1r** [comment]
@gene-roussetos apologies for the delay. Disabling the `Dotdigitalgroup_Inventory` module should work, assuming you ran `bin/magento setup:upgrade` afterwards.
